<?php

namespace Database\Seeders;

use App\Models\RemarkList;
use Illuminate\Database\Seeder;

class RemarkListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $remarks = [
            'Add coolant',
            'Blowdown leak',
            'Bracket alternator problem',
            'Camshaft problem',
            'Casing press. 0 psig',
            'Change conf. to 4/0',
            'Change engine to FP 6xxxx',
            'CO2 removal shut down',
            'Combustion problem',
            'Commissioning',
            'Contract suspension',
            'Control panel error',
            'Coolant level fault',
            'Crankcase problem',
            'Crankshaft problem',
            'Cyl. head problem',
            'Disch. temp. transducer error',
            'Display panel problem',
            'Electricity outage',
            'End commissioning',
            'Engine overhaul',
            'Exhaust manifold broken',
            'False ESD',
            'Flow insufficient',
            'Fuse panel short',
            'Genset trip',
            'GJC start load',
            'GJC trip',
            'High crankcase press.',
            'High disch. press.',
            'High disch. temp.',
            'High exhaust temp.',
            'High liquid',
            'High oil level',
            'High speed',
            'High suct. press.',
            'High water temp.',
            'Lifter problem',
            'Line broken',
            'Line leak',
            'Loss power',
            'Low compression',
            'Low coolant level',
            'Low disch. press.',
            'Low oil level',
            'Low oil press.',
            'Low speed',
            'Low suct. press.',
            'Low suct. press. (MEDCO req.)',
            'Low voltage',
            'Magnetic pickup problem',
            'MEDCO request',
            'Motor starter stuck',
            'MP 5016 trouble',
            'MPI 7117 trouble',
            'PEP request',
            'Perbaikan line bocor',
            'PHE request',
            'PHR request',
            'PLN dips, CO2 removal shut down',
            'PM 1000 hrs',
            'PM 5000 hrs',
            'Press. casing 0 psig',
            'Rear main seal leak',
            'Relay problem',
            'Repair line broken',
            'Repair line leak',
            'Replace alternator',
            'Replace battery',
            'Replace bolt alternator',
            'Replace cable',
            'Replace cable coil',
            'Replace cable coil & coil',
            'Replace cable magnetic pickup',
            'Replace camshaft',
            'Replace coil',
            'Replace coil & spark plug',
            'Replace comp. valve',
            'Replace crankshaft',
            'Replace cyl. head',
            'Replace disch. hose',
            'Replace disch. temp. transducer',
            'Replace display panel',
            'Replace EZRail',
            'Replace fuse',
            'Replace gasket oil pan',
            'Replace hose water pump',
            'Replace KIMRAY',
            'Replace KIMRAY regulator',
            'Replace lifter',
            'Replace magnetic pickup',
            'Replace membrane carburetor',
            'Replace oil seal',
            'Replace relay',
            'Replace rocker arm',
            'Replace spark plug',
            'Replace spark plug & coil',
            'Replace spark plug, cable coil & coil',
            'Replace suct. hose',
            'Replace suct. press. transducer',
            'Replace timing gear',
            'Replace transducer',
            'Replace v-belt',
            'Replace v-belt alternator',
            'Replace water pump',
            'RPM hunting',
            'Source press. 0 psig',
            'Speed hunting',
            'Start commissioning',
            'Suct. press. transducer error',
            'Switch to MP 7xxx',
            'Switch to unit A',
            'Tighten bolt alternator',
            'Timing gear pin broken',
            'Timing gear problem',
            'Transducer error',
            'Trouble camshaft',
            'Trouble crankshaft',
            'Trouble display panel',
            'Trouble lifter',
            'Trouble timing gear',
            'Tubing regulator leak',
            'User request',
            'Water pump leak',
        ];

        // firstOrCreate supaya seeder aman dijalankan ulang (tidak duplikat)
        foreach ($remarks as $remark) {
            RemarkList::firstOrCreate(['remark' => $remark]);
        }
    }
}
