<?php

namespace Database\Seeders;

use App\Models\RemarkList;
use Illuminate\Database\Seeder;

class RemarkListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // remark => tipe (sd, stdby, note - bisa lebih dari satu untuk "STBY and SD")
        $remarks = [
            'Add coolant' => ['note'],
            'Blowdown leak' => ['sd'],
            'Bracket alternator problem' => ['sd'],
            'Camshaft problem' => ['sd'],
            'Casing press. 0 psig' => ['stdby'],
            'Change conf. to 4/0' => ['sd'],
            'Change engine to FP 6xxxx' => ['sd'],
            'CO2 removal shut down' => ['stdby'],
            'Combustion problem' => ['sd'],
            'Commissioning' => ['note'],
            'Contract suspension' => ['note'],
            'Control panel error' => ['sd'],
            'Coolant level fault' => ['sd'],
            'Cooler leak' => ['sd'],
            'Crankcase problem' => ['sd'],
            'Crankshaft problem' => ['sd'],
            'Cyl. head problem' => ['sd'],
            'Disch. temp. transducer error' => ['sd'],
            'Display panel problem' => ['sd'],
            'Electricity outage' => ['note'],
            'End commissioning' => ['note'],
            'Engine overhauling' => ['sd'],
            'Exhaust manifold broken' => ['sd'],
            'False ESD' => ['sd'],
            'Flow insufficient' => ['note'],
            'Fuse panel short' => ['sd'],
            'Gas cooler leak' => ['sd'],
            'Genset trip' => ['stdby'],
            'GJC start load' => ['note'],
            'High crankcase press.' => ['sd'],
            'High disch. press.' => ['sd'],
            'High disch. temp.' => ['sd'],
            'High exhaust temp.' => ['sd'],
            'High liquid' => ['stdby', 'sd'],
            'High oil level' => ['sd'],
            'High speed' => ['sd'],
            'High suct. press.' => ['sd'],
            'High water temp.' => ['sd'],
            'Lifter problem' => ['sd'],
            'Line leak' => ['stdby', 'sd'],
            'Line rupture' => ['stdby', 'sd'],
            'Loss power' => ['sd'],
            'Low compression' => ['sd'],
            'Low coolant level' => ['sd'],
            'Low disch. press.' => ['sd'],
            'Low oil level' => ['sd'],
            'Low oil press.' => ['sd'],
            'Low speed' => ['sd'],
            'Low suct. press.' => ['stdby'],
            'Low suct. press. (MEDCO req.)' => ['stdby'],
            'Low voltage' => ['sd'],
            'Magnetic pickup problem' => ['sd'],
            'MEDCO request' => ['stdby'],
            'Motor starter stuck' => ['sd'],
            'PEP request' => ['stdby'],
            'EMP request' => ['stdby'],
            'PHE request' => ['stdby'],
            'PHR request' => ['stdby'],
            'PLN dips, CO2 removal shut down' => ['stdby'],
            'PM 1000 hrs' => ['sd'],
            'PM 5000 hrs' => ['sd'],
            'Radiator leak' => ['sd'],
            'Rear main seal leak' => ['sd'],
            'Regulator tubing leak' => ['sd'],
            'Relay problem' => ['sd'],
            'Repair line leak' => ['sd'],
            'Repair line rupture' => ['sd'],
            'Replace alternator' => ['sd'],
            'Replace battery' => ['sd'],
            'Replace bolt alternator' => ['sd'],
            'Replace cable coil' => ['sd'],
            'Replace cable coil & coil' => ['sd'],
            'Replace cable coil, coil & spark plug' => ['sd'],
            'Replace cable magnetic pickup' => ['sd'],
            'Replace camshaft' => ['sd'],
            'Replace coil' => ['sd'],
            'Replace coil & spark plug' => ['sd'],
            'Replace comp. valve' => ['sd'],
            'Replace cooler' => ['sd'],
            'Replace crankshaft' => ['sd'],
            'Replace cyl. head' => ['sd'],
            'Replace disch. hose' => ['sd'],
            'Replace disch. temp. transducer' => ['sd'],
            'Replace display panel' => ['sd'],
            'Replace EZRail' => ['sd'],
            'Replace fuse' => ['sd'],
            'Replace gas cooler' => ['sd'],
            'Replace gasket oil pan' => ['sd'],
            'Replace gasket manifold' => ['sd'],
            'Replace hose water pump' => ['sd'],
            'Replace lifter' => ['sd'],
            'Replace magnetic pickup' => ['sd'],
            'Replace membrane carburetor' => ['sd'],
            'Replace oil seal' => ['sd'],
            'Replace pressure control valve' => ['sd'],
            'Replace pressure control valve regulator' => ['sd'],
            'Replace radiator' => ['sd'],
            'Replace relay' => ['sd'],
            'Replace rocker arm' => ['sd'],
            'Replace spark plug' => ['sd'],
            'Replace suct. hose' => ['sd'],
            'Replace suct. press. transducer' => ['sd'],
            'Replace transducer' => ['sd'],
            'Replace v-belt' => ['sd'],
            'Replace v-belt alternator' => ['sd'],
            'Replace water pump' => ['sd'],
            'RPM hunting' => ['sd'],
            'Source press. 0 psig' => ['stdby'],
            'Speed hunting' => ['sd'],
            'Start commissioning' => ['note'],
            'Startup' => ['note'],
            'Suct. press. transducer problem' => ['sd'],
            'Switch to MP 7xxx' => ['sd'],
            'Switch to unit A' => ['stdby'],
            'Timing gear pin broken' => ['sd'],
            'Timing gear problem' => ['sd'],
            'Transducer problem' => ['sd'],
            'Tubing press. 0 psig' => ['stdby'],
            'Gasket manifold leak' => ['sd'],
            'Water pump leak' => ['sd'],
            'Replace bearing altenator' => ['sd'],
        ];

        // updateOrCreate supaya seeder aman dijalankan ulang dan tipe selalu sinkron dengan daftar di atas
        foreach ($remarks as $remark => $types) {
            RemarkList::updateOrCreate(
                ['remark' => $remark],
                ['request_type' => $types],
            );
        }
    }
}
